### ISSUE TITLE
Eigenständiger Node-RED-Node (außerhalb von RedMatic)?

### ISSUE THREAD

**Issue by Poquaruse** [rdmtc/RedMatic-WebApp#25]
Hi!

Vielen Dank für die tolle Software -- mal wieder! 
Wäre es möglich, die RedMatic-WebApp als eigenständigen Node verfügbar zu machen? So könnte man innerhalb einer bestehenden Node-RED-Instanz (bspw. auf einem NAS) ohne Kauf einer CCU3 die WebApp nutzen.

Viele Grüße

**Comment by matthiaskind** [comment]
Hi!

Das fände ich auch spitze. Hab Node-RED schon auf einer VM mit node-red-contrib-ccu laufen und versuche meine CCU möglichst mit wenigen zusätzlichen Add-Ons zu betreiben.
Da wäre es schon toll, die WebApp auch außerhalb RedMatic nutzen zu können.

Gibt's da Pläne in der Richtung?

Gruß
scorpionking

**Comment by hobbyquaker** [comment]
Das ist bereits möglich, er ist nur nicht im Node-RED Palette Manager auffindbar. Das ist Absicht da die Node-RED Macher keine Nodes wollen die von anderen Nodes abhängig sind. Und da RedMatic-WebApp nur im Zusammenspiel mit node-red-contrib-ccu nutzbar ist hab ich ihn dort nicht eingetragen. Ihr könnt die WebApp aber mit `sudo npm install -g RedMatic-WebApp` installieren.

**Comment by matthiaskind** [comment]
Das habe ich bereits versucht. Leider bleibt die Seite weiß, wenn ich die URL aufrufe.
Kann ich das irgendwie debuggen?

Im Quelltext der leeren Seite ist mir aufgefallen, dass im `<head>`-Teil `<base href="/addons/red/app/">` steht. Tatsächlich rufe ich aber `http://<mein server>:1880/nodered/app/?/app` (bzw. `https://<mein server>/nodered/app/?/app` via Reverse Proxy) auf.
Ich vermute, dass deshalb alle Pfade ins Leere laufen.

**Comment by hobbyquaker** [comment]
oh, ah, stimmt, ganz vergessen, hab da den RedMatic Pfad drin. Muss mal schauen wieviel Aufwand das ist das rauszunehmen.

**Comment by hobbyquaker** [comment]
Mit Version 0.3.0 sollte jetzt der Einsatz auch außerhalb von RedMatic möglich sein.

**Comment by matthiaskind** [comment]
Sieht gut aus, funktioniert bei mir. Danke.
