### ISSUE TITLE
WebApp crashes RedMatic - RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by BlackstoneDB12** [rdmtc/RedMatic-WebApp#26]
Hallo,

seit RedMatic V3.0.0 lässt die WebApp RedMatic abstürzen.
Auch wenn alle Inhalte die darstellbar wären deaktiviert sind, ändert das nichts am Verhalten.
[redmatic.2019-03-13T19_12_20.128Z.log.txt](https://github.com/HM-RedMatic/RedMatic-WebApp/files/2963963/redmatic.2019-03-13T19_12_20.128Z.log.txt)

**Comment by hobbyquaker** [comment]
Sollte mit RedMatic 3.1.0 gefixt sein. Bitte gib Bescheid ob es passt.

**Comment by BlackstoneDB12** [comment]
Sehr gut, funktioniert wieder :-)
